# DOWNLOAD
# simultaneous(?)
--concurrent-fragments 32

# FORMAT
# audio only
--extract-audio

# resume partially downloaded files
--continue

# POST PROCESS 
# video thumbnail -> album art
--embed-thumbnail

# embed title, artist, etc.
--embed-metadata

# file name format
--output '~/music/%(title)s - %(artist)s.%(ext)s'

