# DOWNLOAD
# simultaneous(?)
--concurrent-fragments 32

# FORMAT
# audio only
--extract-audio

# resume partially downloaded files
--continue

# skip existing
--no-overwrites

# POST PROCESS 
# video thumbnail -> album art
--embed-thumbnail

# file name format
--output '~/music/%(title)s - %(artist)s.%(ext)s'

